# Generated by Django 5.1 on 2024-09-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
