# Generated by Django 5.1 on 2024-09-18 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0003_student_alter_teacher_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("duration", models.CharField(max_length=20)),
                (
                    "shift",
                    models.CharField(
                        choices=[("M", "Morning"), ("D", "Day")], max_length=1
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth_app.teacher",
                    ),
                ),
            ],
            options={
                "db_table": "course",
                "ordering": ["title"],
            },
        ),
    ]
